### PR TITLE
remove useless hostlisteners

### PR DESCRIPTION
**Pull request by ludohenin**

### CODE REVIEW

**Comment by SekibOmazic** [comment]
@ludohenin Thanks!

**Comment by ludohenin** [comment]
I'm not quite sure what the real use of hostListeners though :)
any idea ?

**Comment by SekibOmazic** [comment]
I used them before like this:

``` JS
@Component({
  selector: 'drag',
  hostListeners: {
    'mousedown': 'onMouseDown($event)'
  }
})
```

but now I prefer:

``` html
<div class="item" (mousedown)="onMouseDown($event)">
```

so I'm not really sure what is the real purpose :-)

**Comment by ludohenin** [comment]
yeah OK, that's what I was thinking, thanks.

**Comment by ibhi** [comment]
I think host listeners is provided as a high level api for the DOM, without touching the DOM. To better understand there was one example from victor savkin victorsavkin.com/post/118372404541/the-core-concepts-of-angular-2 ,  refer the heading hostelement

**Comment by ibhi** [comment]
Also you can have a look at example 3, in my article [here](https://github.com/ibhi/Directives-in-Angular-2.0#example-3-events-and-hostlisteners), where I have setup hostListeners to fire custom event.

**Pull request merged**
